### ISSUE TITLE
JSX whitespace issue

### ISSUE THREAD

**Issue by gaearon** [RReverser/acorn-jsx#13] opened 2015-01-10 13:54 UTC
This is a repost of https://github.com/6to5/6to5/issues/419.

```js
var Foo = React.createClass({
  render() {
    return (
      <span>foo</span>
    );
  }
});

var Bar = React.createClass({
  render() {
    return (
      <div>
        <Foo/> bar
      </div>
    );
  }
});
```

The whitespace between `<Foo/>` and `bar` is missing in the output.

**Comment by gaearon** [comment] 2015-01-10 13:56
Is there any kind of quick temporary fix for this that wouldn't necessitate [the rewrite](https://github.com/6to5/6to5/issues/419#issuecomment-69453944)?

I'd really like this one case fixed, as this is what prevents us from using 6to5, and I already changed build process to use 6to5.

I'm happy to work on it if you can point me in the right direction.

**Comment by RReverser** [comment] 2015-01-10 16:48
As a quick one on your side, you can use method from early days of JSX when it didn't support whitespace output at all - just insert `{' '}` in your code.

I mentioned rewrite because this issue raises up again and again. We had the same with ES6 templates earlier too, and without integrating the same fix, each case requires own step-by-step debugging of simplified reproducible test case just to find where and why it happens. If you want - you can do that on your side now and I'll be happy to accept PR.

**Comment by gaearon** [comment] 2015-01-10 16:50
>As a quick one on your side, you can use method from early days of JSX when it didn't support whitespace output at all - just insert {' '} in your code.

Yeah I was considering that but it's hard to find places in the source code where I might need this, as I have hundreds of components.

>If you want - you can do that on your side now and I'll be happy to accept PR.

I think I'll give it a shot if I have time, and if I find some cheap way to do that, I'll ping you back.

thanks!

**Comment by gaearon** [comment] 2015-01-10 16:57
OTOH grepping for `\w>[ ]` in JSX files should probably be enough.

**Comment by gaearon** [comment] 2015-01-11 15:02
BTW this only seems to happen with self-closing tags.

**Comment by RReverser** [comment] 2015-01-17 13:32
Fixed with [rewrite](https://github.com/RReverser/acorn-jsx/tree/rewrite), I'm just willing to wait for some upstream changes and merge them before release. /cc @sebmck

**Comment by sebmck** [comment] 2015-01-17 13:33
@RReverser Awesome! What about #14? It's a pretty serious issue as it currently breaks source maps.

**Comment by RReverser** [comment] 2015-01-17 13:35
@sebmck Just answered there :)

**Comment by RReverser** [comment] 2015-01-17 13:36
@sebmck But I'd ask not to merge this to 6to5 until I finish some core changes in upstream (want to be sure that nothing will be broken).

**Comment by sebmck** [comment] 2015-01-17 13:36
@RReverser Sure, I'll wait for your go-ahead.

**Comment by gaearon** [comment] 2015-01-17 13:52
Really appreciate you tackling this! Thank you for taking time.

**Comment by RReverser** [comment] 2015-01-17 14:17
Always welcome!

**Comment by gaearon** [comment] 2015-01-22 15:28
:+1:

**Closed** 2015-01-22 15:27 UTC

**Comment by RReverser** [comment] 2015-01-22 15:29
@sebmck I guess we are now good to go. Please note that prefixes are now changed to `JSX` instead of legacy `XJS` (see facebook/esprima#83 for context). Let me know about any issues you encounter after upgrade - I'll be happy to fix 'em.

**Comment by sebmck** [comment] 2015-01-22 21:09
@RReverser Great, thank you! Few merge conflicts but nothing serious, passes the 6to5 and acorn-6to5 test suite so all is good, thanks again!

**Comment by RReverser** [comment] 2015-01-22 21:32
@sebmck Great to hear!
